/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'msinghi' at '7/20/14 8:08 PM' with Gradle 2.0
 *
 * @author msinghi, @date 7/20/14 8:08 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
